# Introduction {#elements}

## R programming language


## RStudio

RStudio is an integrated development environment (IDE) for R that provides an alternative interface to R that has several advantages over other default interfaces. 

## Installation

The first thing you need to do to get started with R is to install it on your computer. R works on pretty much every platform available, including the widely available Windows, Mac OS X, and Linux systems. If you want to watch a step-by-step tutorial on how to install R for Mac or Windows, you can watch these videos:

- [Installation R on Windows](https://www.youtube.com/watch?v=Ohnk9hcxf9M&feature=youtu.be)

- [Installing R on the Mac](https://www.youtube.com/watch?v=uxuuWXU-7UQ&feature=youtu.be)

Next you can install Rstudio. Remember, you must have R already installed before installing Rstudio. If you want to watch a step-by-step watch the vedio [here](https://www.youtube.com/watch?v=bM7Sfz-LADM&feature=youtu.be).

## Main windows

## Setting your working directory

What is working directory?  To find your current working directory type `getwd()` on console.

## Working with R scripts files

Rather than typing R commands into the Console. This allows for **reproducibility**, share scripts with someone else.

To create a new R script

File --> New File --> R Script

Commenting on R scripts

## R packages

### Installation

There is a large community of R users who contribute various packages that do useful things. Before you start using an R package, you must first install it into your environment. There are two ways to install a package

1. 


2.

### Load a package

one time, then load package

## Important things to know about R

1. R is case-sensitive

3. R works with numerous data types. Some of the most basic types to get started are:

    i. **numeric**: decimal values like 8.5
    
    ii. **integers**: natural numbers like 8

    iii. **logical**: Boolean values (TRUE or FALSE)

    iv. **character**: strigs(text) like "statistics"

## Objects

The entities R operates on are technically known as **objects**. There are two types of objects:

1. Data structures

2. Functions

## Getting help



## Variable assignment


## 

## Data permanency and removing objects


